### ISSUE TITLE
缺少vgg16.t7

### ISSUE THREAD

**Issue by qq935925136** [q-zh/absorption#2]
FileNotFoundError: [Errno 2] No such file or directory: '../models/vgg16.t7'

**Comment by qq935925136** [comment]
我已经下载这个文件，并放进models了，还是提示这个错误

**Comment by xuehuapi** [comment]
> 我已经下载了这个文件，并模型了，还是这个提示错误
请问现在问题解决了吗？

**Comment by joker-kor** [comment]
> > 我已经下载了这个文件，并模型了，还是这个提示错误
> > 请问现在问题解决了吗？
The link the author downloaded is now closed.
So I used the pretrained model provided by pytorch.
The modification code can be modified by modifying the init_vgg16 function in solver.py.

    def init_vgg16(self, model_folder):
        """load the vgg16 model feature"""
        if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
style/models/vgg16.t7 -O ' + os.path.join(

            vgglua = models.vgg16(pretrained=True)
            vgg = Vgg16()

            for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
            
                dst.data[:] = src
            torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))

**Comment by joker-kor** [comment]
The link the author downloaded is now closed.
So I used the pretrained model provided by pytorch.
The modification code can be modified by modifying the init_vgg16 function in solver.py.

    def init_vgg16(self, model_folder):
        """load the vgg16 model feature"""
        if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
            vgglua = models.vgg16(pretrained=True)
            vgg = Vgg16()
            for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
                dst.data[:] = src
                torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))

> > 我已经下载了这个文件，并模型了，还是这个提示错误
> > 请问现在问题解决了吗？
The link the author downloaded is now closed.
So I used the pretrained model provided by pytorch.
The modification code can be modified by modifying the init_vgg16 function in solver.py.

    def init_vgg16(self, model_folder):
        """load the vgg16 model feature"""
        if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
            vgglua = models.vgg16(pretrained=True)
            vgg = Vgg16()
            for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
                dst.data[:] = src
                torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))

**Comment by joker-kor** [comment]
> > 我已经下载了这个文件，并模型了，还是这个提示错误
> > 请问现在问题解决了吗？

The link the author downloaded is now closed.
So I used the pretrained model provided by pytorch.
The modification code can be modified by modifying the init_vgg16 function in solver.py.
Don't forget to create the models directory in the parent folder.
#----------------------------------------------------------------------------------------------------
from torchvision import  models

    def init_vgg16(self, model_folder):
        """load the vgg16 model feature"""
        if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
            vgglua = models.vgg16(pretrained=True)
            vgg = Vgg16()
            for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
                dst.data[:] = src
            torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))

**Comment by otaejang** [comment]
> > > 我已经下载了这个文件，并模型了，还是这个提示错误
> > > 请问现在问题解决了吗？
> 
> The link the author downloaded is now closed. So I used the pretrained model provided by pytorch. The modification code can be modified by modifying the init_vgg16 function in solver.py. Don't forget to create the models directory in the parent folder. #---------------------------------------------------------------------------------------------------- from torchvision import models
> 
> ```
> def init_vgg16(self, model_folder):
>     """load the vgg16 model feature"""
>     if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
>         vgglua = models.vgg16(pretrained=True)
>         vgg = Vgg16()
>         for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
>             dst.data[:] = src
>         torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))
> ```

Introducing oneself is done like this. This is a very helpful response.

**Comment by q-zh** [comment]
> > > 我已经下载了这个文件，并模型了，还是这个提示错误
> > > 请问现在问题解决了吗？
> 
> The link the author downloaded is now closed. So I used the pretrained model provided by pytorch. The modification code can be modified by modifying the init_vgg16 function in solver.py. Don't forget to create the models directory in the parent folder. #---------------------------------------------------------------------------------------------------- from torchvision import models
> 
> ```
> def init_vgg16(self, model_folder):
>     """load the vgg16 model feature"""
>     if not os.path.exists(os.path.join(model_folder, 'vgg16.weight')):
>         vgglua = models.vgg16(pretrained=True)
>         vgg = Vgg16()
>         for (src, dst) in zip(vgglua.parameters(), vgg.parameters()):
>             dst.data[:] = src
>         torch.save(vgg.state_dict(), os.path.join(model_folder, 'vgg16.weight'))
> ```

Thank you for your reply!!!
